feat(query): add date_diff function
databendlabs/databend pull request #16560
Opened 2024-10-02 02:36 UTC by chagelo

I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

related to #16534

## Tests

- [x] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

2024-10-03 15:28 UTC, chagelo commented
very confusing, I have registered the date_diff's different func name like diff_years, but it gives me `no function matches signature add_years(Date, Date)` error, passed the unittest, but cann't pass the sqllogic test.

2024-10-08 05:13 UTC, TCeason commented on src/query/functions/tests/it/scalars/testdata/datetime.txt
> +output         : 0
select date_diff(year, to_timestamp('2020-02-29 23:59:59.165575'), to_timestamp('2019-02-28 23:59:59.423179'))

expect -1

2024-10-08 05:14 UTC, TCeason commented on src/query/functions/tests/it/scalars/testdata/datetime.txt
> +output         : -3
I test in snowflake , `select datediff(quarter, to_timestamp('2020-02-29 23:59:59.165575'), to_timestamp('2019-02-28 23:59:59.423179'))` expect -4

2024-10-08 05:15 UTC, TCeason commented on src/query/functions/tests/it/scalars/testdata/datetime.txt
> +output         : 1
select datediff(year, to_timestamp('2023-11-12 09:38:18.165575'), to_timestamp('2025-03-27 21:01:35.423179')) expect 2.

2024-10-08 05:19 UTC, TCeason commented on tests/sqllogictests/suites/query/functions/02_0012_function_datetimes.test
> +1
consider test select DATE_DIFF(YEAR, TO_TIMESTAMP('2023-12-31 09:38:18.165575'), TO_TIMESTAMP('2024-01-01 21:01:35.423179')) the result should be 1.

2024-10-08 05:20 UTC, TCeason commented on tests/sqllogictests/suites/query/functions/02_0012_function_datetimes.test
> +1
Also need to add some tests where the sign is negative

2024-10-08 06:10 UTC, chagelo commented
Sorry, I got you. But, what's the result of `select date_diff(year, to_date('2023-12-31'), to_date('2024-01-01'))`?

2024-10-08 06:26 UTC, TCeason commented
> Sorry, I got you. But, what's the result of `select date_diff(year, to_date('2023-12-31'), to_date('2024-01-01'))`?

Oh, I just mean add a logic test case:

```
query T
SELECT DATE_DIFF(YEAR, to_date('2023-12-31'), to_date('2024-01-01'))
----
1

```

2024-10-08 06:30 UTC, chagelo commented
So what should I do is to fix it to be compatible with Snowflake and add more tests?

2024-10-08 06:33 UTC, TCeason commented
> So what should I do is to fix it to be compatible with Snowflake and add more tests?

Date diff about year just need to evaluate year sub. E.g. 

2023-12-31 2024-01-01 just need to calc year sub.

2024-10-08 06:36 UTC, chagelo commented
Ok, thank you.

TCeason ***@***.***> 于2024年10月8日周二 14:33写道：

> So what should I do is to fix it to be compatible with Snowflake and add
> more tests?
>
> Date diff about year just need to evaluate year sub. E.g.
>
> 2023-12-31 2024-01-01 just need to calc year sub.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/databendlabs/databend/pull/16560#issuecomment-2398966402>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AL4OCSKJ7XXJNNZXDXK7I53Z2N4E7AVCNFSM6AAAAABPGYZISGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOJYHE3DMNBQGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-10 09:41 UTC, TCeason commented on src/query/expression/src/utils/date_helper.rs
> +        diff_months.signum() * diff_months.abs().div_ceil(3)
Now Databen has ToQuarter calc quartrter.

```rust
impl ToNumber<u8> for ToQuarter {
    fn to_number(dt: &DateTime<Tz>) -> u8 {
        (dt.month0() / 3 + 1) as u8
    }
}
```

https://github.com/databendlabs/databend/blob/a58d8b42aec4d38c2cffd40d2e6eb9ac2cf6bc90/src/query/expression/src/utils/date_helper.rs#L499

Directly calc diff and div 3 maybe cause some mistake.

2024-10-11 14:42 UTC, TCeason approved these changes

2024-10-11 14:56 UTC, TCeason requested changes

2024-10-11 14:56 UTC, TCeason commented on tests/sqllogictests/suites/query/functions/02_0012_function_datetimes.test
> +SELECT DATE_DIFF(QUARTER, to_date('2024-01-01'), to_date('2023-06-01'))
Good case. 

```

// Special case handling: If the end date is in the first quarter of the next year, and the start date is in the second quarter or later of the current year, then subtract 1.


let adjusted_quarters2 = if end_date2.year() > start_date2.year() && end_date2.month() <= 3 && start_date2.month() >= 4 {
quarters2 - 1
} else {
quarters2
};

```

2024-10-12 00:54 UTC, TCeason approved these changes
LGTM

2024-10-12 03:23 UTC, TCeason commented
Hi @chagelo  after approving this pr, I see you force-push a commit. What's diff in this commit? just rebase lastest main?

![image](https://github.com/user-attachments/assets/fa4f1819-ba52-493a-bba6-4ffc2648af86)

2024-10-12 03:33 UTC, chagelo commented
Yes

2024-10-12 05:30 UTC, merged

2024-10-12 05:31 UTC, BohuTANG commented
@soyeric128 Documentation need update. Thanks.

2024-10-12 05:32 UTC, BohuTANG commented
@chagelo Thanks to your contribution!